# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sehati' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sehati
  pod 'GoogleSignIn'

  target 'SehatiTests' do
    inherit! :search_paths
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    # Pods for testing
  end

end
